### ISSUE TITLE
In development?

### ISSUE THREAD

**Issue by drmrbrewer** [marians/dwd-weather#3]
Hi dev!

Is this still in development?  Is it likely to be far off working?  Because I just tried installing / using.  I got as far as installing:

	$ sudo pip install dwdweather                                                                               
	Downloading/unpacking dwdweather
	  Downloading dwdweather-0.7.tar.gz
	  Running setup.py (path:/tmp/pip_build_root/dwdweather/setup.py) egg_info for package dwdweather
		
	Installing collected packages: dwdweather
	  Running setup.py install for dwdweather
		
		Installing dwdweather script to /usr/local/bin
	Successfully installed dwdweather
	Cleaning up...

But then running a basic command line fails:

	$ dwdweather stations
	Traceback (most recent call last):
	  File "/usr/local/bin/dwdweather", line 9, in <module>
		load_entry_point('dwdweather==0.7', 'console_scripts', 'dwdweather')()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 351, in load_entry_point
		return get_distribution(dist).load_entry_point(group, name)
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2363, in load_entry_point
		return ep.load()
	  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 2093, in load
		raise ImportError("%r has no %r attribute" % (entry,attr))
	ImportError: <module 'dwdweather' from '/usr/local/lib/python2.7/dist-packages/dwdweather.pyc'> has no 'main' attribute

I'd really love a simple way of accessing DWD data (for my app), and find the data available from DWD's ftp server almost impossible to understand...

Thanks!

**Comment by amotl** [comment]
Dear @marians,

while we have not been able to add PostGIS support (#8) yet, we finally have been able to fold all of our recent amendments and improvements into the stable release `0.8.0` and will continue working from there by further enhancing the internal machinery and gradually adding more features.

The new repository url will be [1] and you might enjoy the changelog at [2] already.

Thank you so much for conceiving this fine Python library, we will be happy to follow in your footsteps. We hereby humbly ask you to modify the README to point to the most reasonable current release as addressed in [3]. We also published the current release to PyPI under the updated name `dwdweather2` [4].

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/dwdweather2
[2] https://github.com/hiveeyes/dwdweather2/blob/master/CHANGES.rst
[3] https://github.com/marians/dwd-weather/issues/8#issuecomment-461732002
[4] https://pypi.org/project/dwdweather2/

**Comment by marians** [comment]
Thanks for you work! I'll add a notice and link to the README to point people to the more useful source.

**Comment by amotl** [comment]
Thanks, Marian!
