### ISSUE TITLE
Add PostGIS support

### ISSUE THREAD

**Issue by amotl** [marians/dwd-weather#8]
Dear Marian,

thanks for caring about and merging #5 the other day and thanks again for conceiving this fine module.

While our endeavors to continue improving this module [1] have been dormant for a while, some things like support for acquisition of data from the "10 minutes" resolution category are still lingering in our fork (34de440a). Also, we are currently into adding support for PostGIS in order to unlock querying the station list using GIS operations as we also will be doing with the station list from [luftdaten.info](https://luftdaten.info/) with [Luftdatenpumpe](https://github.com/hiveeyes/luftdatenpumpe) [2].

The outcome of that will converge into one or more Grafana Dashboards @wetterfrosch is currently working on over at [weather.hiveeyes.org](https://weather.hiveeyes.org/) and we will be happy to share the results if you are still interested in these topics in general. Also, I would like to give some love to the caching subsystem along the lines that you acknowledged there's »_[certainly space for improvement here](https://github.com/marians/dwd-weather#some-notes)_« already.

As you already told us in https://github.com/marians/dwd-weather/pull/5#issuecomment-380057469 that you don't maintain this repository actively any more, we humbly would like to ask how would we could proceed with that. Will you be happy (and still available) to help bringing these changes into mainline by accepting more pull requests from us? Or would you think about passing on the torch if we would tentatively offer irregular maintenance and general housekeeping from time to time?

With kind regards,
Andreas.

[1] https://community.hiveeyes.org/t/open-weather-data/113/20
[2] https://community.hiveeyes.org/t/ldi-data-plane-v2/1412

**Comment by marians** [comment]
Hi @amotl ! Feel free to

1. Fork the code
2. Tell me about it, including a link of the new repo URL

and I will modify the Readme here to let people know.

**Comment by amotl** [comment]
Dear @marians,

we just announced the progress on further development of [1] over at [2]. We are aiming to maintain the package for the next time to come.

As we will take the "Add PostGIS support" issue over to [1], we are closing this here.

With kind regards,
Andreas.

[1] https://github.com/hiveeyes/dwdweather2
[2] https://github.com/marians/dwd-weather/issues/3#issuecomment-498086376
